### ISSUE TITLE
Should ship with default AWS Accounts

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix-Skunkworks/swag-client#1]
See https://github.com/Netflix/security_monkey/blob/develop/data/aws_accounts.json

`swag-client` should ship with those accounts in the proper format.

**Comment by kevgliss** [comment]
@monkeysecurity is the above list something that AWS provides? If they provide it in a consistent format, I would suggest we ship the file with swag-client and then have a command line script to optionally populate swag.
