### ISSUE TITLE
Use AWS organizations to propagate SWAG data. 

### ISSUE THREAD

**Issue by kevgliss** [Netflix-Skunkworks/swag-client#22]

**Comment by gvauter** [comment]
@kevgliss did you have any thoughts on implementation here?  This is something I am currently working on internally, but would be happy to start a PR.

**Comment by kevgliss** [comment]
A PR would be great! Implementation wise, I'd imagine a cli command would be best something similar to:

https://github.com/Netflix-Skunkworks/swag-client/blob/master/swag_client/cli.py#L264

**Comment by gvauter** [comment]
#64 opened to add support for propagating org accounts into SWAG.
