### ISSUE TITLE
Make schema v2 validation lists configurable.

### ISSUE THREAD

**Issue by gvauter** [Netflix-Skunkworks/swag-client#47]
The lists used to validate field in the v2 schema are currently hard coded.  In order to make them generic to can they be moved out to a configuration location?

Possibly a config file in ~/.swag/client.conf or something similar?

PROVIDERS = ['aws', 'gcp', 'azure']
ACCOUNT_TYPES = ['billing', 'security', 'shared-service', 'service']
ACCOUNT_STATUSES = ['created', 'in-progress', 'ready', 'deprecated', 'deleted', 'in-active']
ACCOUNT_ENVIRONMENTS = ['test', 'prod']
ACCOUNT_OWNERS = ['netflix', 'dvd', 'aws', 'third-party']

**Comment by kevgliss** [comment]
Yes they should be moved... a swag.conf sounds reasonable. Would you mind putting together a PR?

**Comment by gvauter** [comment]
Hey @kevgliss sorry for the delay on this!  I played around with the design a bit but I think in the end field validation will either have to be packaged with the pip so all users get the same data (which can be a pain when updating a field), or done on a server-side component.  Otherwise multiple clients could end up with different valid values for a given field and the backend has no way of enforcement.  We ended up building it out server-side as a small REST API that houses all the backend logic and then all "clients" just consume the API.  This also avoids having the clients talk directly to the backend.  If you foresee going towards this design in the future i'd be happy to help on that effort, or if you want me to share what we've got as a "swag" add-on just let me know!

**Comment by kevgliss** [comment]
We do have: https://github.com/Netflix-Skunkworks/swag-api which sounds similar to what you have built. 

Design wise, do you think passing in additional validation during client initialization makes sense? You're right that we could end up with different validations. Does it make sense to have these validations at all in that case? It's one thing to enforce data structure another to enforce data values.

**Comment by gvauter** [comment]
In some cases we could probably get away without doing any data value checking, but I would be a little worried that queries against SWAG might become a bit unreliable.  For example if we don't enforce a list of valid account environments, and someone wants a list of all "prod" accounts, it might miss an account that was entered with an environment of "production". 

I've looked at a few of the integration points for SWAG, such as Security Monkey and Historical.  It looks like those are typically using the S3 backend and the swag_client.  Would you ever see the swag_client becoming a small wrapper around the backend swag-api or do you prefer to have the client interact with the backend directly?

**Comment by kevgliss** [comment]
The vast majority of our use cases for SWAG is read-only. We really only have two services that write data to SWAG (spawnpoint (for account creation), and swag-api). The client itself is really for convenience as we have other non-python users that don't use swag-client at all (again for read-only uses). 

Due to the heavy read-only nature of SWAG, the durability and availability of a backing store like S3 was particularly useful. However, I could see an additional backend for swag-client talking directly to the swag-api as useful. It should be fairly straightforward to implement (requests for json, caching, etc.,).

I'm not sure if this is something we would use for our apps but I would be open to merging in a PR if you would find it useful.

**Comment by gvauter** [comment]
Ok makes sense, and the majority of our use cases are read-only as well.  I guess to get back to the original issue - should I put together a PR to remove the data value checks from the V2 schema, or does it make more sense for non Netflix users to work off a fork with values specific to their organization?

**Comment by kevgliss** [comment]
I think if we could move those values to a configuration, perhaps on client initialization, that would allow us to keep the same code base. In that case the default would have no data value checks for those fields unless explicitly supplied. 

If you wanted additional guarantees,  you could force the client to use the rest API which in turn would have those values specified.

**Comment by gvauter** [comment]
Sorry - just getting back around to this!  I'll start on PR for this as you described.

Any chance of `spawnpoint (for account creation)` making its way to OSS 😁 ?

**Comment by kevgliss** [comment]
cc @willbengtson for spawnpoint :-)

**Comment by gvauter** [comment]
Closing, see #60
