### ISSUE TITLE
How to get started with the client

### ISSUE THREAD

**Issue by angelbarrera92** [Netflix-Skunkworks/swag-client#49]
Hi!

I just trying to understand how  this client works. When i saw this project i imagined that is used to track or to get a accounts list over an AWS root account and store it on S3, file or dynamodb. Thats correct?

I am using the common environment variables *(**AWS_DEFAULT_REGION** and **AWS_PROFILE**)* with an admin account. 

But i dont know how to get the user list :(

I have installed it using:

```bash
$ export AWS_DEFAULT_REGION=eu-west-1
$ export AWS_PROFILE=my_profile
$ virtualenv -p python3 .env
$ source .env/bin/activate
$ pip install swag-client
$ swag-client -v DEBUG list
warning: Backend file does not exist, creating... Path: /home/angel/work/devops/accounts.json
debug: Fetching items. Path: /home/angel/work/devops/accounts.json
Account Name    Account Number
--------------  ----------------
$ cat accounts.json 
[]
```
What i am doing wrong?

**Comment by kevgliss** [comment]
Hi @angelbarrera92 sorry a bit late on the response here.

You've got the general idea right. We use SWAG as a central repository for account metadata. We have 100s of accounts, with so many accounts even simple things like naming become a challenge, one tool says something is prod, another says it's prod-staging, etc. which is right? We use SWAG to resolve and disambiguate these problems, at the end of day most tools just need an account number, unfortunately 12 char strings are very human friendly. SWAG attempts to bridge that gap. 

Additionally, SWAG can store information for infrastructure services that need to store account level metadata. 

Again the above is all up to you to under, SWAG just provides a schema for organizing this data and some ways to store and retrieve that information. 

We do have #22 open that might help you pre populate some of this data if you're using AWS organizations. But SWAG is not strictly AWS specific and could be used for other cloud providers.

Hope this helps!
